In [6]:
import pandas as pd
import numpy as np
import io   
import requests
import datetime as dt
import copy

In [7]:
data1 = pd.read_csv("[Final Window]괴물쥐_935176016.csv", encoding='CP949')
data2 = pd.read_csv("[Final Window]랄로_903242294.csv", encoding='CP949')
data3 = pd.read_csv("[Final Window]미라지_895415119.csv", encoding='CP949')
data4 = pd.read_csv("[Final Window]미라지_914887347.csv", encoding='CP949')
data5 = pd.read_csv("[Final Window]소니쇼_913699132.csv", encoding='CP949')
data6 = pd.read_csv("[Final Window]소니쇼_941561128.csv", encoding='CP949')
data7 = pd.read_csv("[Final Window]앰비션_937548014.csv", encoding='CP949')
data8 = pd.read_csv("[Final Window]얍얍_916232844.csv", encoding='CP949')
data9 = pd.read_csv("[Final Window]얍얍_918848624.csv", encoding='CP949')
data10 = pd.read_csv("[Final Window]우왁굳_937608573.csv", encoding='CP949')
data11 = pd.read_csv("[Final Window]이태준_916331457.csv", encoding='CP949')
data12 = pd.read_csv("[Final Window]인간젤리_925275340.csv", encoding='CP949')
data13 = pd.read_csv("[Final Window]재슥짱_942215773.csv", encoding='CP949')
data14 = pd.read_csv("[Final Window]주키니_937786846.csv", encoding='CP949')
data15 = pd.read_csv("[Final Window]주키니_942840952.csv", encoding='CP949')
data16 = pd.read_csv("[Final Window]치킨쿤_918712592.csv", encoding='CP949')
data17 = pd.read_csv("[Final Window]파카_922834094.csv", encoding='CP949')
data18 = pd.read_csv("[Final Window]풍월량_924112733.csv", encoding='CP949')
data19 = pd.read_csv("[Final Window]얍얍_918848624.csv", encoding='CP949')
data20 = pd.read_csv("[Final Window]풍월량_926484159.csv", encoding='CP949')

In [8]:
data = pd.concat([data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11, data12, data13, data14, data15, data16, data17, data18, data19])
data

,시간,채팅내용,시청자ID,하이라이트 여부,채팅수,참여비율,시간정규화,어절수,음절수,낱글자수,채팅당 어절수,채팅당 음절수,채팅당 낱글자수,Hscore,Nscore
0,00:00:00,,,X,0.0,0.000000,0.000034,0,0,0,0.000000,0.00,0.0,0.0,0.000000
1,00:00:01,,,X,0.0,0.000000,0.000069,0,0,0,0.000000,0.00,0.0,0.0,0.000000
2,00:00:02,,,X,0.0,0.000000,0.000103,0,0,0,0.000000,0.00,0.0,0.0,0.000000
3,00:00:03,,,X,0.0,0.000000,0.000138,0,0,0,0.000000,0.00,0.0,0.0,0.000000
4,00:00:04,,,X,0.0,0.000000,0.000172,0,0,0,0.000000,0.00,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41665,11:34:25,3주 에반데 그립습니다........ 3년임,"뿌리28, 얍줌마, 무야호0",X,3.0,0.003194,0.999904,5,21,0,1.666667,7.00,0.0,0.0,0.789034
41666,11:34:26,3주 에반데 그립습니다........ 3년임,"뿌리28, 얍줌마, 무야호0",X,3.0,0.003194,0.999928,5,21,0,1.666667,7.00,0.0,0.0,0.789034
41667,11:34:27,3주 에반데 그립습니다........ 3년임 수술들어간다는데..,"뿌리28, 얍줌마, 무야호0 입롤하기시작한박찬호",X,4.0,0.005405,0.999952,7,31,0,1.750000,7.75,0.0,0.0,0.811497
41668,11:34:28,NaN,NaN,X,0.0,0.000000,0.999976,0,0,0,0.000000,0.00,0.0,0.0,0.000000
41669,11:34:29,NaN,NaN,X,0.0,0.000000,1.000000,0,0,0,0.000000,0.00,0.0,0.0,0.000000

In [9]:
data = data.drop(['시간','채팅내용', '시청자ID'], axis=1)

In [10]:
data

,하이라이트 여부,채팅수,참여비율,시간정규화,어절수,음절수,낱글자수,채팅당 어절수,채팅당 음절수,채팅당 낱글자수,Hscore,Nscore
0,X,0.0,0.000000,0.000034,0,0,0,0.000000,0.00,0.0,0.0,0.000000
1,X,0.0,0.000000,0.000069,0,0,0,0.000000,0.00,0.0,0.0,0.000000
2,X,0.0,0.000000,0.000103,0,0,0,0.000000,0.00,0.0,0.0,0.000000
3,X,0.0,0.000000,0.000138,0,0,0,0.000000,0.00,0.0,0.0,0.000000
4,X,0.0,0.000000,0.000172,0,0,0,0.000000,0.00,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
41665,X,3.0,0.003194,0.999904,5,21,0,1.666667,7.00,0.0,0.0,0.789034
41666,X,3.0,0.003194,0.999928,5,21,0,1.666667,7.00,0.0,0.0,0.789034
41667,X,4.0,0.005405,0.999952,7,31,0,1.750000,7.75,0.0,0.0,0.811497
41668,X,0.0,0.000000,0.999976,0,0,0,0.000000,0.00,0.0,0.0,0.000000
41669,X,0.0,0.000000,1.000000,0,0,0,0.000000,0.00,0.0,0.0,0.000000

In [11]:
data['하이라이트 여부'] = data['하이라이트 여부'].replace('O', '1')
data['하이라이트 여부'] = data['하이라이트 여부'].replace('X', '0')
data

,하이라이트 여부,채팅수,참여비율,시간정규화,어절수,음절수,낱글자수,채팅당 어절수,채팅당 음절수,채팅당 낱글자수,Hscore,Nscore
0,0,0.0,0.000000,0.000034,0,0,0,0.000000,0.00,0.0,0.0,0.000000
1,0,0.0,0.000000,0.000069,0,0,0,0.000000,0.00,0.0,0.0,0.000000
2,0,0.0,0.000000,0.000103,0,0,0,0.000000,0.00,0.0,0.0,0.000000
3,0,0.0,0.000000,0.000138,0,0,0,0.000000,0.00,0.0,0.0,0.000000
4,0,0.0,0.000000,0.000172,0,0,0,0.000000,0.00,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
41665,0,3.0,0.003194,0.999904,5,21,0,1.666667,7.00,0.0,0.0,0.789034
41666,0,3.0,0.003194,0.999928,5,21,0,1.666667,7.00,0.0,0.0,0.789034
41667,0,4.0,0.005405,0.999952,7,31,0,1.750000,7.75,0.0,0.0,0.811497
41668,0,0.0,0.000000,0.999976,0,0,0,0.000000,0.00,0.0,0.0,0.000000
41669,0,0.0,0.000000,1.000000,0,0,0,0.000000,0.00,0.0,0.0,0.000000

In [12]:
data = data.astype({'하이라이트 여부':'int', '채팅수':'float', '어절수':'float', '음절수':'float', '낱글자수':'float'})

In [33]:
data = pd.DataFrame(data)

In [34]:
# def make_dataset(data, label, window_size = 20):
#     feature_list = []
#     label_list = []
#     for i in range(len(data) - window_size):
#         feature_list.append(np.array(data.iloc[i:i+window_size]))
#         label_list.append(np.array(label.iloc[i+window_size]))
#     return np.array(feature_list), np.array(label_list)

In [35]:
feature_cols = ['채팅수','참여비율','시간정규화','어절수','음절수','낱글자수','채팅당 어절수','채팅당 음절수','채팅당 낱글자수','Hscore','Nscore']
label_cols = ['하이라이트 여부']

In [36]:
train_feature = data[feature_cols]
train_label = data[label_cols]

In [37]:
# train_feature, train_label = make_dataset(train_feature, train_label, 20)

In [38]:
# paka_feature = train_feature

In [39]:
# paka_feature.shape

In [40]:
from sklearn.model_selection import train_test_split
x_train, x_valid, y_train, y_valid = train_test_split(train_feature, train_label, test_size =0.2)
x_train.shape,x_valid.shape

((391851, 11), (97963, 11))

In [41]:
test_feature = data[feature_cols]
test_label = data[label_cols]

In [42]:
# test_feature.shape, test_label.shape

In [43]:
# from keras.models import Sequential
# from keras.layers import Dense
# from keras.callbacks import EarlyStopping, ModelCheckpoint
# from keras.layers import LSTM
# from keras.layers import Dense
# from keras.models import Sequential
# from keras.layers import Dense
# from keras.optimizers import Adam
# import pandas as pd
# import numpy as np
# import keras
# from numpy import array
# from keras.models import Sequential
# from keras.layers import Dense, LSTM, GRU
# from keras.layers import Dense, Dropout
# from keras.datasets import imdb
# from keras.layers.embeddings import Embedding
# from keras.preprocessing import sequence
# from keras.activations import sigmoid

       하이라이트 여부
13765         0
9025          0
21343         1
10153         0
14109         0
...         ...
10629         0
16312         0
1834          0
14172         0
21609         0

[97963 rows x 1 columns]

In [44]:
# from keras. models import load_model
# model = load_model('modeL.h5')

In [45]:
# yhat = model.predict_classes(train_feature)

In [46]:
# yhat

In [47]:
# pred = pd.DataFrame(yhat)

In [48]:
# pred.to_csv('이름.csv', encoding = 'cp949')

In [52]:
from sklearn.svm import SVC
 
svm_model = SVC(kernel='rbf', C=8, gamma=0.1)
 
svm_model.fit(X_train_std, y_train) # SVM 분류 모델 훈련

<ipython-input-52-139b25109b34>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train) # kNN 분류기를 훈련셋으로 훈련시킵니다.

KNeighborsClassifier(n_neighbors=1)

In [54]:
print(knn.score(x_valid,y_valid))

0.8694609189183672

In [ ]:
from keras.models import load_model
model.save('SVM.h5')

이 위에까지

In [ ]:
import matplotlib.pyplot as plt
k_list = range(1,101)
accuracies = []
for k in k_list:
  knn = KNeighborsClassifier(n_neighbors = k)
  knn.fit(x_train, y_train)
  accuracies.append(knn.score(x_valid, y_valid))
plt.plot(k_list, accuracies)
plt.xlabel("k")
plt.ylabel("Validation Accuracy")
plt.title("Breast Cancer Classifier Accuracy")
plt.show()

<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)

<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)
<ipython-input-59-c11989a5acaf>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train, y_train)

In [33]:
from keras.models import load_model
model = load_model('LSTM.h5')

In [35]:
model.fit(train_feature,train_label,epochs = 5, batch_size=1)

Epoch 1/5
18982/18982 [==============================] - 41s 2ms/step - loss: 0.1817 - accuracy: 0.9354
Epoch 2/5
18982/18982 [==============================] - 41s 2ms/step - loss: 0.1799 - accuracy: 0.9349
Epoch 3/5
18982/18982 [==============================] - 42s 2ms/step - loss: 0.1806 - accuracy: 0.9346
Epoch 4/5
18982/18982 [==============================] - 42s 2ms/step - loss: 0.1849 - accuracy: 0.9343
Epoch 5/5
18982/18982 [==============================] - 42s 2ms/step - loss: 0.1811 - accuracy: 0.9358

In [36]:
model.save('LSTM추가.h5')

In [45]:
# paka = pd.read_csv('[Final Window]파카_920049094.csv', encoding = 'cp949')
# paka

In [46]:
# paka_feature= ['채팅수','참여비율','시간정규화','어절수','음절수','낱글자수','채팅당 어절수','채팅당 음절수','채팅당 낱글자수','Hscore','Nscore']

In [47]:
# pred = model.predict_classes(paka_feature)
# pred

WARNING:tensorflow:Model was constructed with shape (None, 20, 11) for input KerasTensor(type_spec=TensorSpec(shape=(None, 20, 11), dtype=tf.float32, name='gru_input'), name='gru_input', description="created by layer 'gru_input'"), but it was called on an input with incompatible shape (None, 1, 11).

C:\Users\junho\anaconda3\lib\site-packages\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [48]:
# pred = pd.DataFrame(pred)
# pred

       0
0      1
1      1
2      1
3      0
4      0
...   ..
18996  0
18997  0
18998  0
18999  0
19000  0

[19001 rows x 1 columns]

In [50]:
# pred.to_csv('PAKA.GRU 스케일후.csv')

##########